# Generated by Django 4.0.4 on 2022-04-19 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='muscles',
            field=models.ManyToManyField(blank=True, related_name='exercises', to='exercises.muscle'),
        ),
    ]
